/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAtualizacoesRouteImport } from './routes/_authenticated/atualizacoes'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedBackupsRouteImport } from './routes/_authenticated/backups'
import { Route as AuthenticatedBaselinesRouteImport } from './routes/_authenticated/baselines'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedConformidadeRouteImport } from './routes/_authenticated/conformidade'
import { Route as AuthenticatedDispositivosIndexRouteImport } from './routes/_authenticated/dispositivos.index'
import { Route as AuthenticatedDispositivosIdRouteImport } from './routes/_authenticated/dispositivos.$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtualizacoesRoute =
  AuthenticatedAtualizacoesRouteImport.update({
    id: '/atualizacoes',
    path: '/atualizacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBackupsRoute = AuthenticatedBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBaselinesRoute = AuthenticatedBaselinesRouteImport.update({
  id: '/baselines',
  path: '/baselines',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConformidadeRoute =
  AuthenticatedConformidadeRouteImport.update({
    id: '/conformidade',
    path: '/conformidade',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDispositivosIndexRoute =
  AuthenticatedDispositivosIndexRouteImport.update({
    id: '/dispositivos/',
    path: '/dispositivos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDispositivosIdRoute =
  AuthenticatedDispositivosIdRouteImport.update({
    id: '/dispositivos/$id',
    path: '/dispositivos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/atualizacoes': typeof AuthenticatedAtualizacoesRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/backups': typeof AuthenticatedBackupsRoute
  '/baselines': typeof AuthenticatedBaselinesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conformidade': typeof AuthenticatedConformidadeRoute
  '/dispositivos/$id': typeof AuthenticatedDispositivosIdRoute
  '/dispositivos/': typeof AuthenticatedDispositivosIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/atualizacoes': typeof AuthenticatedAtualizacoesRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/backups': typeof AuthenticatedBackupsRoute
  '/baselines': typeof AuthenticatedBaselinesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conformidade': typeof AuthenticatedConformidadeRoute
  '/': typeof AuthenticatedIndexRoute
  '/dispositivos/$id': typeof AuthenticatedDispositivosIdRoute
  '/dispositivos': typeof AuthenticatedDispositivosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/atualizacoes': typeof AuthenticatedAtualizacoesRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/backups': typeof AuthenticatedBackupsRoute
  '/_authenticated/baselines': typeof AuthenticatedBaselinesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/conformidade': typeof AuthenticatedConformidadeRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/dispositivos/$id': typeof AuthenticatedDispositivosIdRoute
  '/_authenticated/dispositivos/': typeof AuthenticatedDispositivosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/atualizacoes'
    | '/auditoria'
    | '/backups'
    | '/baselines'
    | '/configuracoes'
    | '/conformidade'
    | '/dispositivos/$id'
    | '/dispositivos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/atualizacoes'
    | '/auditoria'
    | '/backups'
    | '/baselines'
    | '/configuracoes'
    | '/conformidade'
    | '/'
    | '/dispositivos/$id'
    | '/dispositivos'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/atualizacoes'
    | '/_authenticated/auditoria'
    | '/_authenticated/backups'
    | '/_authenticated/baselines'
    | '/_authenticated/configuracoes'
    | '/_authenticated/conformidade'
    | '/_authenticated/'
    | '/_authenticated/dispositivos/$id'
    | '/_authenticated/dispositivos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atualizacoes': {
      id: '/_authenticated/atualizacoes'
      path: '/atualizacoes'
      fullPath: '/atualizacoes'
      preLoaderRoute: typeof AuthenticatedAtualizacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backups': {
      id: '/_authenticated/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof AuthenticatedBackupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/baselines': {
      id: '/_authenticated/baselines'
      path: '/baselines'
      fullPath: '/baselines'
      preLoaderRoute: typeof AuthenticatedBaselinesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conformidade': {
      id: '/_authenticated/conformidade'
      path: '/conformidade'
      fullPath: '/conformidade'
      preLoaderRoute: typeof AuthenticatedConformidadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dispositivos/': {
      id: '/_authenticated/dispositivos/'
      path: '/dispositivos'
      fullPath: '/dispositivos/'
      preLoaderRoute: typeof AuthenticatedDispositivosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dispositivos/$id': {
      id: '/_authenticated/dispositivos/$id'
      path: '/dispositivos/$id'
      fullPath: '/dispositivos/$id'
      preLoaderRoute: typeof AuthenticatedDispositivosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAtualizacoesRoute: typeof AuthenticatedAtualizacoesRoute
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedBackupsRoute: typeof AuthenticatedBackupsRoute
  AuthenticatedBaselinesRoute: typeof AuthenticatedBaselinesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedConformidadeRoute: typeof AuthenticatedConformidadeRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDispositivosIdRoute: typeof AuthenticatedDispositivosIdRoute
  AuthenticatedDispositivosIndexRoute: typeof AuthenticatedDispositivosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAtualizacoesRoute: AuthenticatedAtualizacoesRoute,
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedBackupsRoute: AuthenticatedBackupsRoute,
  AuthenticatedBaselinesRoute: AuthenticatedBaselinesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedConformidadeRoute: AuthenticatedConformidadeRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDispositivosIdRoute: AuthenticatedDispositivosIdRoute,
  AuthenticatedDispositivosIndexRoute: AuthenticatedDispositivosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
